---
deployment:
  tasks:
    - export DEPLOYPATH=/home/vuscgco1/public_html/
    - /bin/sh -c 'echo "DEPLOY TEST $(date)" > "${DEPLOYPATH}deploy-check.txt"'
    - /bin/sh -c 'echo "HEAD: $(git rev-parse --short HEAD)" >> "${DEPLOYPATH}deploy-check.txt"'
    - /bin/sh -c 'pwd >> "${DEPLOYPATH}deploy-check.txt"'
    - /bin/sh -c 'ls -la >> "${DEPLOYPATH}deploy-check.txt"'